# Generated by Django 3.2.7 on 2021-09-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
