# Generated by Django 3.2.7 on 2021-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_rename_category_blogpost_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='catagory',
            field=models.CharField(choices=[('FA', 'FASHION'), ('FD', 'FOOD'), ('MU', 'MUSIC'), ('TR', 'TRAVEL')], max_length=300),
        ),
    ]
