# Generated by Django 3.2.7 on 2021-09-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_alter_blogpost_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='catagory',
            field=models.CharField(choices=[('Fashion', 'FASHION'), ('Food', 'FOOD'), ('Music', 'MUSIC'), ('Travel', 'TRAVEL')], max_length=300),
        ),
    ]
